name: Build, Test and publish to Dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10.12'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    - name: Run Unit Tests with Pytest
      run: python -m pytest
      
  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: skalador/python-ticket-system:latest
          
      - name: Generate Software Bill of Materials 
        uses: anchore/sbom-action@v0.14.3
        with: 
          image: skalador/python-ticket-system:latest
          format: spdx-json
          artifact-name: sbom.spdx.json
          upload-artifact: true
